// Generated by https://quicktype.io

export interface PlaceDetails {
    html_attributions: any[];
    result:            Result;
    status:            string;
}

export interface Result {
    formatted_phone_number: string;
    name:                   string;
    rating:                 number;
}
